name: hometech
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_size_text: ^3.0.0
  image: 4.1.7
  google_fonts: ^6.1.0
  icons_plus: ^5.0.0
  provider: ^6.1.1
  google_nav_bar: ^5.0.6
  simple_circular_progress_bar: ^1.0.2
  language_picker: ^0.4.3
  url_launcher: ^6.2.5
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.10
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  firebase_storage: ^11.6.11
  image_picker: ^1.0.7
  http: ^1.2.1
  smooth_page_indicator: ^1.1.0
  firebase_ui_database: ^1.4.2
  firebase_database: ^10.5.0
  open_filex: ^4.4.0
  path_provider: ^2.1.2
  flutter_launcher_icons: ^0.13.1
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/documents/
